languageCode = "en-us"
publishDir = "docs"

baseurl = "https://mattrossman.github.io/madrid-blog"
title = "Matt in Madrid"
author = "Matt Rossman"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "home"
description = "aether Hugo theme for blogs"
homeimg = ""