languageCode = "en-us"

baseurl = "https://madrid.mattrossman.com/"
title = "Matt in Madrid"
author = "Matt Rossman"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "home"
description = "Spring 2019 Study Abroad"
homeimg = ""