languageCode = "en-us"
publishDir = "docs"

baseurl = "https://madrid.mattrossman.com"
title = "Matt in Madrid"
author = "Matt Rossman"
canonifyurls = false
paginate = 3
theme = "aether"

[params]
brand = "home"
description = "aether Hugo theme for blogs"
homeimg = ""